### ISSUE TITLE
Is it okay to use this in closed source applications?

### ISSUE THREAD

**Issue by vroad** [wighawag/openfl-stage3d#23]
Is this still GPL? Or, is it okay to use this code with less-strict licenses like MIT? I've heard that current Stage3D impl is based on the code from this repo.
I've also found Stage3D layer code in https://github.com/away3d/away3d-core-openfl and says nothing specifically about licensing of Stage3D layer.

We've moved source code to OpenFL repo long time ago because we thought it was licensed under MIT license.
 @jgranick is now thinking about switching to new code base, partly because of licencing issue, but I cannot switch to that one immediately. So I want to keep using code which originated from this repo.

**Comment by wighawag** [comment]
Hi vroad, sorry, should have put a license there, 
it is not GPL, it is zlib

**Comment by vroad** [comment]
Thank you for answering my question.

**Comment by vroad** [comment]
@larsiusprime adviced me to get permissions from all contributors so I'll ask them about this. Even if it's unlikely to get sued, it'd be better to avoid issues.

@longde123 @player-03 @m22spencer @Beeblerox @Greg209 @drkibitz
Is everybody okay to release code with zlib license?

I remember seeing @Greg209 and @player-03 in OpenFL/Away3d repo. Maybe I don't need to mention them.

**Comment by player-03** [comment]
I'm fine with it, but isn't this code kind of out-of-date? OpenFL has its own implementation now.

**Comment by vroad** [comment]
It's outdated, but I'm wondering if it causes legal issues because contributors may want this to be GPL.

https://github.com/openfl/openfl/issues/1224
